### PR TITLE
Initial prototype with CI and test placeholder

### PR DESCRIPTION
**Pull request by ryukzak**
Close:
- #1

### CODE REVIEW

**Comment by DontCallMeShurley** [comment]
add a request to return the full texture of the cube (6 faces collected in texture format)

**Comment by ryukzak** [comment]
> add a request to return the full texture of the cube (6 faces collected in texture format)

It will be better to do it in a separated PR. Please, write for me an issue with additional requirements because right now I don't fully understand what you need. Maybe -- scheme with face placement on the single image will help.

**Comment by DontCallMeShurley** [comment]
I mean some like UV Mapping
In this ref explain not bad - http://ilkinulas.github.io/development/unity/2016/05/06/uv-mapping.html

**Comment by DontCallMeShurley** [comment]
To put it simply, I want to be able to return a full cube texture with a texture map

**Comment by ryukzak** [comment]
Looks good. Please, describe preferable API for it in a new issue. What params it should receive and what type of image it should return.

**Review by DontCallMeShurley — APPROVED** [review]
Need a new imp on new issue

**Pull request merged**
